apiVersion: v1
kind: Service
metadata:
  name: cube-service
spec:
  type: LoadBalancer
  selector:
    app: cube-service
  ports:
  - port: 5005
    targetPort: 5005
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cube-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: cube-service
  template:
    metadata:
      labels:
        app: cube-service
    spec:
      containers:
      - name: cube-service
        image: cubecai/kube:caiservice
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 5005
